apiVersion: v1
kind: Service

metadata:
  name: corporatewebsite-service

spec:
  type: NodePort

  selector:
    app: corporatewebsite

  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30082